log:
  level: 'DEBUG'
global_parameters:
  trajectory_history_window_length: 20
  trajectory_future_window_length: 30
global_path: '/workspace'
model_storage_path: '/workspace/model_storage'
data_process:
  input_path: 'dataset'
  output_path: 'internal'
  n_processes: 8
  visualize: False
  parameters:
    trajectory_min_history_window_length: 5
    object_trajectory_min_history_window_length: 5
    object_trajectory_min_future_window_length: 3
    object_distance_threshold: 100
    centerline_radius_scale: 3.0
    add_neighboring_lanes: True
    lane_radius_scale: 5.0
    min_lane_radius: 50.0
raster:
  data_process:
    input_path: 'internal'
    output_path: 'internal_raster'
    visualize: True
    debug_visualize: True
    parameters:
      agent_view_window_size: 224
      object_shape: [6, 6]
      centerline_point_shape: [6, 6]
      gauss_kernel_size: 25
      gauss_kernel_sigma: 4
      max_neighbours: 20
  train_tf:
    train_input_path: 'internal/train'
    val_input_path: 'internal/val'
    output_path: 'model_storage/heatmap_tf'
    n_workers: 8
    model_name: 'home-forecster-baseline'
    parameters:
      epochs: 20
      lr: 0.01
      batch_size: 128
      sched_step: 10
      sched_gamma: 0.1
  train_heatmap:
    train_input_path: 'TODO'
    val_input_path: 'TODO'
    model_name: 'home-baseline'
    n_workers: 8
    resume: True
    starting_checkpoint_name: 'last.ckpt'
    parameters:
      epochs: 15
      sampler_targets: 6
      sampler_radius: 2
      batch_size: 16
      augmentation: True
      base_lr: 0.001
      sched_step: 4
      sched_gamma: 0.5
model:
  name: 'vectornet'
  config_path: 'configs/model_config.yaml'
evaluation:
  input_path: 'internal_graph'
  output_path: 'result'
  model_path: 'model_storage/vectornet_traj_scoring'
  visualize: False

